import '~/styles/globals.css';

import { Inter } from 'next/font/google';
import { Web3Provider } from '~/providers';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Web3Provider>
        <body className={`font-sans ${inter.variable}`}>{children}</body>
      </Web3Provider>
    </html>
  );
}
